const corpusData = [
    {
        "File": "2025_12_11_What_did_you_do.TextGrid",
        "AudioFile": "2025_12_11_What_did_you_do.mp3",
        "Time": "0:00:06 - 0:00:09",
        "StartMs": 6263.969999999999,
        "EndMs": 9312.91,
        "Orthography": "Өдр сән болва мендвт, тана өдр ямаран болва?",
        "Transcription": "ödr sän bol-va mendvt tana ödr yamaran bol-va",
        "Gloss": "day good COP2-PST hello, 2SG.GEN day how COP2-PST",
        "Translation": "Hello, my day was good, how was yours?"
    },
    {
        "File": "2025_12_11_What_did_you_do.TextGrid",
        "AudioFile": "2025_12_11_What_did_you_do.mp3",
        "Time": "0:00:15 - 0:00:17",
        "StartMs": 15222.48,
        "EndMs": 16846.329999999998,
        "Orthography": "Сән сән сән көдлмштән",
        "Transcription": "sän sän sän ködlmsh-t=än",
        "Gloss": "good good good work-DAT=RP",
        "Translation": "Good, good, good, to your work."
    },
    {
        "File": "2025_12_11_What_did_you_do.TextGrid",
        "AudioFile": "2025_12_11_What_did_you_do.mp3",
        "Time": "0:00:17 - 0:00:18",
        "StartMs": 17240.870000000003,
        "EndMs": 18253.24,
        "Orthography": "Көдлмш дала бәәнә?",
        "Transcription": "ködlmsh dala bää-nä-∅",
        "Gloss": "work many COP1-NPST-3SG",
        "Translation": "Do you have a lot of work?"
    },
    {
        "File": "2025_12_11_What_did_you_do.TextGrid",
        "AudioFile": "2025_12_11_What_did_you_do.mp3",
        "Time": "0:00:32 - 0:00:33",
        "StartMs": 31702.44,
        "EndMs": 32513.85,
        "Orthography": "Зул болха",
        "Transcription": "zul bol-xa",
        "Gloss": "zul COP2-INF",
        "Translation": "It will be Zul."
    },
    {
        "File": "2025_12_11_What_did_you_do.TextGrid",
        "AudioFile": "2025_12_11_What_did_you_do.mp3",
        "Time": "0:00:33 - 0:00:39",
        "StartMs": 33203.88,
        "EndMs": 39007.6,
        "Orthography": "Декабрин арвн дөрвн арвн дөрвдгч арвн дөрвдгчт",
        "Transcription": "dekabr-in arvn dörvn arvn dörvdgch arvn dörvdgch-t",
        "Gloss": "december-GEN ten four ten fourth ten fourth-DAT",
        "Translation": "on December 14th"
    },
    {
        "File": "2025_12_11_What_did_you_do.TextGrid",
        "AudioFile": "2025_12_11_What_did_you_do.mp3",
        "Time": "0:00:45 - 0:00:46",
        "StartMs": 44729.75,
        "EndMs": 45980.25,
        "Orthography": "борцг идхм",
        "Transcription": "bortsg id-x-m",
        "Gloss": "boortsog eat-INF-COP.AFF",
        "Translation": "I'll eat boortsog."
    },
    {
        "File": "2025_12_11_What_did_you_do.TextGrid",
        "AudioFile": "2025_12_11_What_did_you_do.mp3",
        "Time": "0:00:48 - 0:00:50",
        "StartMs": 48118.89,
        "EndMs": 50378.5,
        "Orthography": "Мини гергн борцг кенә",
        "Transcription": "mini gergn bortsg ke-nä-∅",
        "Gloss": "1SG.GEN wife boortsog make-NPST-3SG",
        "Translation": "My wife makes boortsog."
    },
    {
        "File": "2025_12_11_What_did_you_do.TextGrid",
        "AudioFile": "2025_12_11_What_did_you_do.mp3",
        "Time": "0:00:51 - 0:00:55",
        "StartMs": 50817.23,
        "EndMs": 54662.86,
        "Orthography": "мадн борцг кеһәд идхм арвн дөрв арвн дөрвнд",
        "Transcription": "madn bortsg ke-ghäd id-x-m arvn dörv arvn dörvn-d",
        "Gloss": "1PL.GEN boortsog make-CVB.PRF eat-INF-COP.AFF ten four ten four-DAT",
        "Translation": "We will eat our boortsog on the 14th."
    },
    {
        "File": "2025_12_11_What_did_you_do.TextGrid",
        "AudioFile": "2025_12_11_What_did_you_do.mp3",
        "Time": "0:00:56 - 0:00:59",
        "StartMs": 55765.38,
        "EndMs": 58989.22,
        "Orthography": "енчн кезә енчн ендр ендр кедү болҗана",
        "Transcription": "enchn kezä enchn endr endr kedü bol-ja-na",
        "Gloss": "this when this today today how.much COP2-PROG-NPST",
        "Translation": "Today she is making a lot."
    },
    {
        "File": "2025_12_11_What_did_you_do.TextGrid",
        "AudioFile": "2025_12_11_What_did_you_do.mp3",
        "Time": "0:00:59 - 0:01:01",
        "StartMs": 59424.21,
        "EndMs": 60963.520000000004,
        "Orthography": "арвн негн болҗана тиигхлә",
        "Transcription": "arvn negn bol-ja-na tiig-xlä",
        "Gloss": "ten one COP2-PROG-NPST do.so-CVB.SUCC",
        "Translation": "She will do so on the eleventh."
    },
    {
        "File": "2025_12_11_What_did_you_do.TextGrid",
        "AudioFile": "2025_12_11_What_did_you_do.mp3",
        "Time": "0:01:02 - 0:01:05",
        "StartMs": 61597.36,
        "EndMs": 64906.98999999999,
        "Orthography": "һурвн өдрин дара һурвн өдрин дара",
        "Transcription": "ghurvn ödr-in dara ghurvn ödr-in dara",
        "Gloss": "three day-GEN next.to three day-GEN next.to ",
        "Translation": "There are just three days left."
    },
    {
        "File": "2025_12_11_What_did_you_do.TextGrid",
        "AudioFile": "2025_12_11_What_did_you_do.mp3",
        "Time": "0:01:07 - 0:01:10",
        "StartMs": 67415.16,
        "EndMs": 69807.56,
        "Orthography": "һурвн өдрин дара арвн дөрвн болх",
        "Transcription": "ghurvn ödr-in dara arvn dörvn bol-x",
        "Gloss": "three day-GEN next.to ten four COP2-INF",
        "Translation": "In three days, it will be the 14th."
    },
    {
        "File": "2025_12_11_What_did_you_do.TextGrid",
        "AudioFile": "2025_12_11_What_did_you_do.mp3",
        "Time": "0:01:11 - 0:01:16",
        "StartMs": 71456.40000000001,
        "EndMs": 76433.66,
        "Orthography": "тадна тер утнасн егчтә харһсн таасгду",
        "Transcription": "tadna ter utnasn egch-tä xargh-sn taas-gd-u ",
        "Gloss": "2PL.GEN DIST Utnasn older.sister-SOC meet-HAB approve-PASS-???",
        "Translation": "Utnasn approved of meeting you all."
    },
    {
        "File": "2025_12_11_What_did_you_do.TextGrid",
        "AudioFile": "2025_12_11_What_did_you_do.mp3",
        "Time": "0:01:16 - 0:01:20",
        "StartMs": 76433.66,
        "EndMs": 80468.90999999999,
        "Orthography": "сән болву сән болву таасгду",
        "Transcription": "sän bol-v-u sän bol-v-u taas-gd-u",
        "Gloss": "good COP2-PST-??? good COP2-PST-??? approve-PASS-???",
        "Translation": "It went well, you were approved of."
    },
    {
        "File": "2025_12_11_What_did_you_do.TextGrid",
        "AudioFile": "2025_12_11_What_did_you_do.mp3",
        "Time": "0:01:23 - 0:01:26",
        "StartMs": 83405.24,
        "EndMs": 86380.31999999999,
        "Orthography": "Сән сән йир сән",
        "Transcription": "sän sän yir sän",
        "Gloss": "good good very good",
        "Translation": "Good, good, very good."
    },
    {
        "File": "2025_04_17_Disney.TextGrid",
        "AudioFile": "2025_04_17_Disney.mp3",
        "Time": "0:00:00 - 0:00:02",
        "StartMs": 0.0,
        "EndMs": 2299.56,
        "Orthography": "ендр би йир байрта бәәнәв",
        "Transcription": "endr bi yir bayrta bää-nä-v",
        "Gloss": "today 1SG very happy COP1-NPST-1SG",
        "Translation": "Today has been good."
    },
    {
        "File": "2025_04_17_Disney.TextGrid",
        "AudioFile": "2025_04_17_Disney.mp3",
        "Time": "0:00:05 - 0:00:08",
        "StartMs": 4847.72,
        "EndMs": 8342.04,
        "Orthography": "дала-әдл наадһа үзвв",
        "Transcription": "dalaädl naadgha üz-v-v",
        "Gloss": "many thing see-PST-1SG",
        "Translation": "I saw lots of cool things."
    },
    {
        "File": "2025_04_17_Disney.TextGrid",
        "AudioFile": "2025_04_17_Disney.mp3",
        "Time": "0:01:04 - 0:01:05",
        "StartMs": 64010.44,
        "EndMs": 65026.69,
        "Orthography": "би",
        "Transcription": "bi",
        "Gloss": "1SG",
        "Translation": "I"
    },
    {
        "File": "2025_04_17_Disney.TextGrid",
        "AudioFile": "2025_04_17_Disney.mp3",
        "Time": "0:01:10 - 0:01:16",
        "StartMs": 70152.33,
        "EndMs": 76220.42,
        "Orthography": "би сафари гидг һазрт күрәд дала адусн үзвв",
        "Transcription": "bi safari gi-dg ghazr-t kür-äd dala adusn üz-v-v",
        "Gloss": "1SG safari say-HAB land-DAT reach-CVB.PRF animal see-PST-1SG",
        "Translation": "I went on a safari and saw lots of animals."
    },
    {
        "File": "2025_04_17_Disney.TextGrid",
        "AudioFile": "2025_04_17_Disney.mp3",
        "Time": "0:01:22 - 0:01:35",
        "StartMs": 82230.09999999999,
        "EndMs": 95005.96,
        "Orthography": "би сафари гидг сафари гидг һазрт күрәд дала адусн үзвв",
        "Transcription": "bi safari gi-dg safari gi-dg ghazr-t kür-äd dala adusn üz-v-v",
        "Gloss": "1S safari say-HAB safari say-HAB land-DAT reach-CVB.PRF animal see-PST-1SG",
        "Translation": "I went on a safari and saw lots of animals."
    },
    {
        "File": "2025_04_17_Disney.TextGrid",
        "AudioFile": "2025_04_17_Disney.mp3",
        "Time": "0:02:13 - 0:02:15",
        "StartMs": 133353.41,
        "EndMs": 135005.64,
        "Orthography": "олн зүсн шовуд",
        "Transcription": "oln züsn shovu-d",
        "Gloss": "many kind bird-PL",
        "Translation": "many kinds of birds"
    },
    {
        "File": "2025_04_17_Disney.TextGrid",
        "AudioFile": "2025_04_17_Disney.mp3",
        "Time": "0:02:17 - 0:02:21",
        "StartMs": 137276.72,
        "EndMs": 140816.34,
        "Orthography": "би олн зүсн шовуд үзвв",
        "Transcription": "bi oln züsn shovu-d üz-v-v",
        "Gloss": "1S many kind bird-PL see-PST-1SG",
        "Translation": "I saw many kinds of birds."
    },
    {
        "File": "2025_04_17_Disney.TextGrid",
        "AudioFile": "2025_04_17_Disney.mp3",
        "Time": "0:02:22 - 0:02:26",
        "StartMs": 141667.99,
        "EndMs": 145967.78,
        "Orthography": "олн зүсн шовуд үзвв",
        "Transcription": "oln züsn shovu-d üz-v-v",
        "Gloss": "many kind bird-PL see-PST-1SG",
        "Translation": "I saw many kinds of birds."
    },
    {
        "File": "2025_04_17_Disney.TextGrid",
        "AudioFile": "2025_04_17_Disney.mp3",
        "Time": "0:02:52 - 0:03:04",
        "StartMs": 172124.84,
        "EndMs": 183578.61,
        "Orthography": "дәкәд бар бар бар арслң мөчн",
        "Transcription": "däkäd bar bar bar arslng möchn",
        "Gloss": "more tiger tiger tiger lion monkey",
        "Translation": "And tigers, lions, and monkeys too."
    },
    {
        "File": "2025_03_06_Monk.TextGrid",
        "AudioFile": "2025_03_06_Monk.mp3",
        "Time": "0:00:00 - 0:00:04",
        "StartMs": 0.0,
        "EndMs": 4312.97,
        "Orthography": "нег дәкч, лама хол һазрт зуульчлв",
        "Transcription": "neg däkc lama xol ghazr-t zuulycl-v  ",
        "Gloss": "one time monk distant land-DAT travel-PST1",
        "Translation": "Once upon a time, a monk went on a journey to a very far-off place.\n"
    },
    {
        "File": "2025_03_06_Monk.TextGrid",
        "AudioFile": "2025_03_06_Monk.mp3",
        "Time": "0:00:08 - 0:00:13",
        "StartMs": 7691.94,
        "EndMs": 12578.64,
        "Orthography": "хаалһнь хол, аһарнь нигт будта билә\n",
        "Transcription": "хааlgһ-ny хоl аgһаr-ny nigt bud-ta bi-lä\n",
        "Gloss": "road-POSS.3 far air-POSS.3 very fog-COM COP1-PST1",
        "Translation": "The road was long and the weather very foggy."
    },
    {
        "File": "2025_03_06_Monk.TextGrid",
        "AudioFile": "2025_03_06_Monk.mp3",
        "Time": "0:00:16 - 0:00:23",
        "StartMs": 16230.039999999999,
        "EndMs": 22778.210000000003,
        "Orthography": "хаалһдан дала цаган үрәһәд, тиигәд лама дотран зовад бәәв",
        "Transcription": "хааlgһ-d-аn dаlа tsаg-аn ürä-gһäd, tiig-äd lаmа dotr-an zov-аd bää-v.\n",
        "Gloss": "path-REFL.POSS.DAT much time-POSS.REFL.ACC lose-CVB.ANT do-CVB.ANT lama inside-REFL.POSS.ACC worry-CVB.ANT COP1-PST1",
        "Translation": "Because it was taking so long, the monk began to get worried.\n"
    },
    {
        "File": "2025_03_06_Monk.TextGrid",
        "AudioFile": "2025_03_06_Monk.mp3",
        "Time": "0:00:27 - 0:00:30",
        "StartMs": 26616.85,
        "EndMs": 29872.85,
        "Orthography": "үзгән геечкв гиҗ лама санв",
        "Transcription": "üzg-än gее-ck-v gi-j lаmа sаn-v",
        "Gloss": "pen-POSS.REFL.ACC lose-COMPL-PST1 say-CVB.IPFV monk think-PST1",
        "Translation": "He thought that he was lost."
    },
    {
        "File": "2025_03_06_Monk.TextGrid",
        "AudioFile": "2025_03_06_Monk.mp3",
        "Time": "0:00:33 - 0:00:40",
        "StartMs": 33309.7,
        "EndMs": 39893.4,
        "Orthography": "Тиигәд йовад йовҗ лам нег олн күн бәәх бәәшңгтал күрв.\n",
        "Transcription": "tiigäd yоv-ad yоv-j lam neg oln kün bää-х bääšnggtаl kür-v",
        "Gloss": "thus come-CVB.ANT come-CVB.IMPFV monk one many people stay-IRR building arrive-PST1",
        "Translation": "Finally, he arrived at a camp full of people."
    },
    {
        "File": "2025_03_06_Monk.TextGrid",
        "AudioFile": "2025_03_06_Monk.mp3",
        "Time": "0:00:44 - 0:00:48",
        "StartMs": 44318.34,
        "EndMs": 47644.350000000006,
        "Orthography": "әмтнә бәәдлнь йир әәлтә билә",
        "Transcription": "ämtn-ä bädl-ny jir ääl-tä bi-lä",
        "Gloss": "people-GEN appearance-POSS.3 very fear-COM COP1-PST2",
        "Translation": "The people looked strange.\n"
    },
    {
        "File": "2025_03_06_Monk.TextGrid",
        "AudioFile": "2025_03_06_Monk.mp3",
        "Time": "0:00:52 - 0:00:54",
        "StartMs": 51627.29,
        "EndMs": 54486.7,
        "Orthography": "лам тедниг таньсн го",
        "Transcription": "lam tedn-ig tany-sn go\n",
        "Gloss": "monk 3PL-ACC recognize-PTCP.PST NEG",
        "Translation": "He did not recognize them."
    },
    {
        "File": "2025_03_06_Monk.TextGrid",
        "AudioFile": "2025_03_06_Monk.mp3",
        "Time": "0:00:58 - 0:01:03",
        "StartMs": 57890.33,
        "EndMs": 62919.03,
        "Orthography": "мөрн деерән сууҗаһад герин терзәр шаһаһад хәләв",
        "Transcription": "mörn deer-än cuu-ja-ghad ger-in terz-är sagha-gһаd хälä-v\n",
        "Gloss": "horse on-POSS.REFL.ACC sit-CVB.IPFV-CVB.ANT house-GEN window-INST look-CVB.ANT look-PST1",
        "Translation": "On his horse, the monk looked through the window of a house."
    },
    {
        "File": "2025_03_06_Monk.TextGrid",
        "AudioFile": "2025_03_06_Monk.mp3",
        "Time": "0:01:07 - 0:01:12",
        "StartMs": 66822.81,
        "EndMs": 71637.8,
        "Orthography": "дотр-нь нег домбр цокчасн күүкд күн үзгдвә",
        "Transcription": "dotr-ny neg dombr tsok-ca-sn küükd kün üz-gd-vä ",
        "Gloss": "inside-POSS.3 one dombra hit-PROG-PTCP.PST female person see-PASS-PST1",
        "Translation": "He saw a woman inside the house. She was playing dombra.\n"
    },
    {
        "File": "2025_03_06_Monk.TextGrid",
        "AudioFile": "2025_03_06_Monk.mp3",
        "Time": "0:01:17 - 0:01:22",
        "StartMs": 76791.99,
        "EndMs": 81783.1,
        "Orthography": "тер күүкд күн ламыг үзәд гүүҗ ирәд мендлв",
        "Transcription": "ter küükd kün lam-ig üz-äd güü-j ir-äd mendl-v\n",
        "Gloss": "that female person monk-ACC see-PTCP.PST run-CVB.IPFV come-CVB.ANT greet-PST1",
        "Translation": "Soon the women came out of the house. She ran to him and greeted him.\n"
    },
    {
        "File": "2025_03_06_Monk.TextGrid",
        "AudioFile": "2025_03_06_Monk.mp3",
        "Time": "0:01:25 - 0:01:29",
        "StartMs": 85358.52,
        "EndMs": 88867.92,
        "Orthography": "күндтә ах, та ирвтә?\" гиҗ сурв",
        "Transcription": "künd-tä ax ta ir-v-tä gi-j sur-v",
        "Gloss": "respect-COM brother 2PL come-PST1-2PL say-CVB.IPFV ask-PST1",
        "Translation": "“Dear brother, is it you that has arrived?” The woman said."
    },
    {
        "File": "2025_03_06_Monk.TextGrid",
        "AudioFile": "2025_03_06_Monk.mp3",
        "Time": "0:01:34 - 0:01:38",
        "StartMs": 94222.77,
        "EndMs": 97515.03,
        "Orthography": "күн һарч ирәд мөрнь тосад авла",
        "Transcription": "kün ghar-c ir-äd mör-ny tos-ad av-la",
        "Gloss": "person exit-CVB.IPFV come-CVB.ANT horse-POSS.3 receive.CVB.ANT take.PST2",
        "Translation": "The woman’s family took away his horse for him."
    },
    {
        "File": "2025_03_06_Monk.TextGrid",
        "AudioFile": "2025_03_06_Monk.mp3",
        "Time": "0:01:42 - 0:01:45",
        "StartMs": 101639.29000000001,
        "EndMs": 105148.52,
        "Orthography": "гер дотран дуудад чигәһәр тоова",
        "Transcription": "ger dotr-an duud-ad cigä-ghär too-va",
        "Gloss": "house inside-POSS.REFL.ACC invite-CVB.ANT kumis-INS treat-PST1",
        "Translation": "They invited him in, and offered him a cup of kumis.\n"
    },
    {
        "File": "2025_03_06_Monk.TextGrid",
        "AudioFile": "2025_03_06_Monk.mp3",
        "Time": "0:01:49 - 0:01:52",
        "StartMs": 108652.05,
        "EndMs": 111871.87,
        "Orthography": "эн юн һазрви? лама сурҗ",
        "Transcription": "en yun ghazrvi lama cur-j",
        "Gloss": "this what place monk ask-CVB.IPFV",
        "Translation": "‘What village is this?’ asked the monk."
    },
    {
        "File": "2025_03_06_Monk.TextGrid",
        "AudioFile": "2025_03_06_Monk.mp3",
        "Time": "0:01:57 - 0:02:01",
        "StartMs": 116819.32999999999,
        "EndMs": 120726.51999999999,
        "Orthography": "махс мах бард гиҗ хәрү өгв",
        "Transcription": "maxs max bard gi-j xärü ög-v",
        "Gloss": "Makhs Makh Bard say-CVB.IPFV reply give-PST1",
        "Translation": "“Makhs Makh Bard, it is called,” was the reply.\n"
    },
    {
        "File": "2025_03_06_Monk.TextGrid",
        "AudioFile": "2025_03_06_Monk.mp3",
        "Time": "0:02:05 - 0:02:10",
        "StartMs": 125166.86,
        "EndMs": 130014.78,
        "Orthography": "лама чигәһән ууһад дуусна хөөнь зальврхан эклв",
        "Transcription": "lama cigä-ghän uu-ghad duus-na xöö-ny zalyvrx-an ekl-v",
        "Gloss": "monk kumis-POSS.REFL.ACC drink-CVB.ANT finish-NPST after.POSS.3 pray-? begin-PST1",
        "Translation": "After finishing his drink, the monk began to say prayers."
    },
    {
        "File": "2025_03_06_Monk.TextGrid",
        "AudioFile": "2025_03_06_Monk.mp3",
        "Time": "0:02:15 - 0:02:21",
        "StartMs": 134536.89,
        "EndMs": 140904.16999999998,
        "Orthography": "ном умшад эклсн цагтан тер әмтн (күмс) күүнә сүмсн болва",
        "Transcription": "nom umš-ad ekl-sn tsag-tan ter ämtn (küms) küün-ä cümsn bol-va\n",
        "Gloss": "book read-CVB.ANT begin-PTCP.PST time-POSS.REFL.DAT DIST people (people) people-GEN spirit COP2-PST1",
        "Translation": "As soon as he began, the people around turned into spirits."
    },
    {
        "File": "2025_03_06_Monk.TextGrid",
        "AudioFile": "2025_03_06_Monk.mp3",
        "Time": "0:02:25 - 0:02:28",
        "StartMs": 145261.25,
        "EndMs": 148079.03,
        "Orthography": "тер бәәшңг эҗ го бәәҗ",
        "Transcription": "ter bääšngg ej go bääj\n",
        "Gloss": "DIST village empty completely COP1-PTCP.IMFV",
        "Translation": "The village was abandoned."
    },
    {
        "File": "2025_03_06_Monk.TextGrid",
        "AudioFile": "2025_03_06_Monk.mp3",
        "Time": "0:02:33 - 0:02:38",
        "StartMs": 152636.1,
        "EndMs": 157991.62999999998,
        "Orthography": "кермнә толһа болн һосин өскәһәс нань юмн үлдсн го ",
        "Transcription": "kermn-ä tolgha boln ghos-in öskä-ghäs nany yumn üldsn go",
        "Gloss": "squirrel-GEN head and shoe-GEN heel-ABL other thing remain-CVB.ANT NEG",
        "Translation": "Only the head of a squirrel and a shoe heel were left"
    },
    {
        "File": "2025_09_25_Kalmykia.TextGrid",
        "AudioFile": "2025_09_25_Kalmykia.mp3",
        "Time": "0:00:19 - 0:00:26",
        "StartMs": 19203.24,
        "EndMs": 25594.59,
        "Orthography": "гертән гертән сулд цагар ямаран юм келәд келәд келҗ болна",
        "Transcription": "ger-t=än ger-t=än suld tsag-ar yamaran yum kel-äd kel-äd kel-j bol-na-∅",
        "Gloss": "house-DAT=RP house-DAT=RP free time-INST how thing speak-CVB.PRF speak-CVB.PRF speak-CVB.NPFV COP2-NPST-3SG",
        "Translation": "Living in Kalmykia, what did you do in your free time?"
    },
    {
        "File": "2025_09_25_Kalmykia.TextGrid",
        "AudioFile": "2025_09_25_Kalmykia.mp3",
        "Time": "0:00:27 - 0:00:36",
        "StartMs": 26519.37,
        "EndMs": 35931.53,
        "Orthography": "би хальмгт сулд цагтан сулд цагтан көгҗм даслав",
        "Transcription": "bi xal'mg-t suld tsag-t=an suld tsag-t=an kögjm das-la-v",
        "Gloss": "1SG Kalmykia-DAT free time-DAT=RP free time-DAT=RP music study-PST.PRF-1SG",
        "Translation": "During my free time in Kalmykia, I studied music."
    },
    {
        "File": "2025_09_25_Kalmykia.TextGrid",
        "AudioFile": "2025_09_25_Kalmykia.mp3",
        "Time": "0:00:39 - 0:00:41",
        "StartMs": 38789.78,
        "EndMs": 40948.1,
        "Orthography": "көгҗм дасхт дурта биләв",
        "Transcription": "kögjm das-x-t dur-ta bi-lä-v",
        "Gloss": "music study-INF-DAT love COP1-PST.PRF-1SG",
        "Translation": "I loved studying music."
    },
    {
        "File": "2025_09_25_Kalmykia.TextGrid",
        "AudioFile": "2025_09_25_Kalmykia.mp3",
        "Time": "0:00:43 - 0:00:50",
        "StartMs": 42893.659999999996,
        "EndMs": 49759.25,
        "Orthography": "дәкәд еврәннь нәәҗнртәһән хамдан наддг биләвидн",
        "Transcription": "däkäd evr=än=n' nääj-nr-tä=ghän xamdan nad-dg bi-lä-vidn",
        "Gloss": "more self=RP=POSS.3SG friend-PL-SOC=RP always play-HAB COP1-PST.PRF-1PL",
        "Translation": "And my friends and I would always play together."
    },
    {
        "File": "2025_09_25_Kalmykia.TextGrid",
        "AudioFile": "2025_09_25_Kalmykia.mp3",
        "Time": "0:00:50 - 0:00:54",
        "StartMs": 50047.75,
        "EndMs": 54040.0,
        "Orthography": "харһад сәәхн суудг биләвидн",
        "Transcription": "xar-ghad sääxn suu-dg bi-lä-vidn",
        "Gloss": "meet-CVB.PRF beautiful sit-HAB COP1-PST.PRF-1PL",
        "Translation": "It was always beautiful (?)"
    }
];